name: example
description: "Example for the Flutter AI Toolkit."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.4.4

dependencies:
  flutter:
    sdk: flutter
  flutter_ai_toolkit:
    path: ..
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
