name: flutter_ai_toolkit_example
description: "Flutter AI Toolkit Example"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.4

dependencies:
  flutter:
    sdk: flutter
  flutter_ai_toolkit:
    path: ..
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.3
  firebase_core: ^3.4.0
  firebase_vertexai: ^0.2.3
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
