name: flutter_ai_toolkit
description: "A set of AI chat-related widgets for your Flutter app targeting mobile, desktop and web."
version: 0.1.1
homepage: https://github.com/csells/flutter_ai_toolkit

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.2
  google_generative_ai: ^0.4.3
  flutter_markdown_selectionarea: ^0.6.17+1
  image_picker: ^1.1.2
  mime: ^1.0.6
  google_fonts: ^6.2.1
  file_selector: ^1.0.3
  cross_file: ^0.3.4+2
  firebase_vertexai: ^0.2.3
  gap: ^3.0.1
  universal_platform: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
